# for this to work, an Nginx Ingress Controller must be deploed on the cluster
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: someingress
  labels:
    name: someingress
  annotations:
    # the below annotation is used to re-write the path when it is routing to a service.
    # without this annotation, the ingress would route: subdomain.mydomain.com/some/path -> someClusterIpService:80/some/path
    # with this annotation defined, it instead will route: subdomain.mydomain.com/some/path -> someClusterIpService:80/
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: subdomain.mydomain.com
    http:
      paths:
      - pathType: Prefix
        path: "/some/path"
        backend:
          service:
            name: someClusterIpService # the name of the service
            port: 
              number: 80 # the port of the service

  - host: another.mydomain.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: anotherClusterIpService
            port: 
              number: 80