# IMPORTANT!!! You do not want to store the secrets as is in your repo, 
# even though they're encoded in base64, it DOESN'T mean they're encrypted!
# This is just an example.

apiVersion: v1
kind: Secret
metadata:
  name: somesecret
data:
  # Values need to be in base64 (in linux it can be encoded like this: echo -n <MYSTR> | base64)
  SOME_SECRET_VAR: aGVsbG8gd29ybGQ=
  ANOTHER_SECRET_VAR: c29tZSBzdHJpbmc=
