# Pod is the most basic object, it defines what container you want to run.
# Usually you wouldn't use it but rather define a "Deployment" object that has more options.

kind: Pod
apiVersion: v1
metadata:
  name: somepod
  labels:
    a: someValue
    b: anotherValue

spec:
  containers:
    - name: somename
      image: nginx
      # defining resource limits and requests
      resources:
        # these are the resources that will be allocated for the pod on init  
        requests:
          cpu: "500m" # this is 0.5 CPU. 1 CPU unit equals to: 1 AWS vCPU/1 GCP Core/1 Azure vCore.
          memory: "512Mi"
        # these will be the absolute limit for the container to use.
        limits:
          cpu: 1 # if a container goes beyond cpu limit it will be throttled
          memory: "1Gi" # if a container goes beyound memory limit it will be KILLED!
      # exposing a port    
      ports:
        - containerPort: 80

      ## OPTIONAL  

      # overriding ENTRYPOINT and CMD  
      command: ["sleep"] # corresponds to ENTRYPOINT in docker
      args: ["10"] # corresponds to CMD in docker

      # setting environment variables
      env:
        - name: MY_ENV_VAR
          value: some value
        # setting a single env var from a configMap
        - name: VAR_FROM_CONFIG_MAP
          valueFrom:
            configMapKeyRef:
              name: someconfigmap # name of the config map
              key: SOME_VAR # name of the env var we want to use
        # setting a single env var from a secret
        - name: VAR_FROM_SECRET
          valueFrom:
            secretKeyRef:
              key: SOME_SECRET_VAR
      # setting multiple environment variables from a ConfigMap or a Secret
      envFrom:
      - configMapRef:
          name: someconfigmap # name of configmap. This will create the env vars "SOME_VAR" & "ANOTHER_VAR", as specified in the f-configmap-examply.yml
      - secretRef:
          name: somesecret # name of the secret
      
      volumes:
      # attaching configMap to a volume (to be used as file)
      - name: volumeForAppConfig
        configMap:
          name: someconfigmap
      # attaching secret to a volume
      - name: volumeForSecret
        secret:
          secretName: somesecret

      # run this specific container as user 1000    
      securityContext:
        runAsUser: 1000
  # run all containers as user 1000
  securityContext:
    runAsUser: 1000
    capabilities:
      add: ["MAC_ADMIN"] # add capabilities to the running process
  
  # will mount token of the specified serviceAccount to: /var/run/secrets/kubernetes.io/serviceaccount
  serviceAccount: someServiceAccount 
  
  # toleration for a taint (you can "taint" a node with a value, and only pods that can "tolerate" it will be scheduled there)
  tolerations:
    - key: "sometaintkey"
      value: "sometaintvalue"
      operator: "Equal"
      effect: "NoSchedule"
            