# Pod is the most basic object, it defines what container you want to run.
# Usually you wouldn't use it but rather define a "Deployment" object that has more options.

kind: Pod
apiVersion: v1
metadata:
  name: somepod
  labels:
    a: someValue
    b: anotherValue

spec:
  containers:
    - name: somename
      image: nginx
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
      ports:
        - containerPort: 80
      command: ["sleep"] # corresponds to ENTRYPOINT in docker
      args: ["10"] # corresponds to CMD in docker