apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: somepvc
spec:
  resources:
    requests:
      storage: "1Gi"
  # for more information about accessModes, see the persistent volume example
  accessModes:
    - ReadWriteOnce
  # In case we want PV to be dynamically provisioned, we can use a storage class
  storageClassName: somestorageclass # the storage class is defined in p-storageclass-example.yml